name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # every Sunday at midnight
  workflow_dispatch:

jobs:
  industrial_ci:
    if: github.event.pull_request.draft == false  # only run on non-draft PRs
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      ADDITIONAL_DEBS: 'apt-utils dialog'
      CATKIN_LINT: pedantic
      CMAKE_ARGS: -DCMAKE_BUILD_TYPE=Release
      PARALLEL_TESTS: 1
      PYLINT_ARGS: '--output-format=parseable --errors-only --disable=method-hidden'
      PYLINT_CHECK: true
      ROS_REPO: main

    strategy:
      matrix:
        include:
          - { ROS_DISTRO: noetic }

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - uses: ros-industrial/industrial_ci@master
        with:
          config: ${{toJSON(matrix)}}